[build]
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabi]
rustflags = [
  "-C", "linker=arm-none-eabi-gcc",
  "-C", "link-arg=-Wl,-Tlink.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-mthumb",
  "-C", "link-arg=-mcpu=cortex-m4",
  "-C", "link-arg=-mgeneral-regs-only",
  "-C", "link-arg=-lc",
  "-C", "link-arg=-lgcc",
  "-C", "link-arg=-Wl,--allow-multiple-definition",
]