default:
	@echo "Building the Design Document"
	@pandoc --number-sections -F mermaid-filter --pdf-engine=tectonic -o 2024_eCTF_UIUC_Design_Document.pdf \
	hide_protocol.md \
	misc_protocol.md \
	security_requirements.md